import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ArrowRightIcon } from '@heroicons/react/24/outline';
import "./globals.css";
import React from "react";

//import { inter } from '@/app/ui/fonts';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
